version: "3.9"

services:

  steedos-enterprise:
    image: steedos/steedos-enterprise:latest
    container_name: steedos-enterprise
    ports:
      - "80:80"    
      - "443:443"  
      - "9001:9001"  
    environment:
      - ROOT_URL=http://127.0.0.1
      - STEEDOS_LICENSE=trial
      - NPM_CACHE_ENABLED=true
      - NPM_CACHE_PACKAGE_CONTENT=true
      - NPM_REGISTRY_URL=https://registry.npmmirror.com
    tty: true
    volumes:
      - "./storage:/steedos-storage"
  